"""Convert an original PNG to bounded native 16x16 RGB565 presentation metadata.

Requires Pillow. Source assets are supplied explicitly; nothing is downloaded.
Lanczos preserves shape; optional Floyd-Steinberg diffusion targets the
M5Stack's RGB332 canvas or RGB565. Pixels are transported as RGB565, with a
row mask for transparency. RGB332 keeps the original Core's RAM usage bounded.
"""
import argparse
import base64
import hashlib
import json
from pathlib import Path
from PIL import Image, ImageOps

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--source', type=Path, required=True)
parser.add_argument('--name', required=True)
parser.add_argument('--credit', required=True)
parser.add_argument('--output', type=Path, required=True)
parser.add_argument('--preview', type=Path)
parser.add_argument('--dither', action='store_true')
parser.add_argument('--palette', choices=['rgb332','rgb565'], default='rgb332')
args = parser.parse_args()
source = Image.open(args.source).convert('RGBA')
bounds = source.getchannel('A').getbbox()
if not bounds:
    raise ValueError('Empty source icon')
small = ImageOps.contain(source.crop(bounds), (16, 16), Image.Resampling.LANCZOS)
icon = Image.new('RGBA', (16, 16))
icon.paste(small, ((16-small.width)//2, (16-small.height)//2))
values = [[list(icon.getpixel((x,y))[:3]) for x in range(16)] for y in range(16)]
mask, packed = [], bytearray()
preview = Image.new('RGBA', (16,16))
for y in range(16):
    row = 0
    for x in range(16):
        visible = icon.getpixel((x,y))[3] >= 128
        if visible:
            row |= 0x8000 >> x
        levels = [7,7,3] if args.palette=='rgb332' else [31,63,31]
        quantized = [round(max(0,min(255,values[y][x][i]))*levels[i]/255) for i in range(3)]
        rgb = [round(quantized[i]*255/levels[i]) for i in range(3)]
        native = [round(rgb[i]*[31,63,31][i]/255) for i in range(3)]
        color = (native[0]<<11)|(native[1]<<5)|native[2]
        packed.extend(color.to_bytes(2,'big'))
        preview.putpixel((x,y),(*rgb,255 if visible else 0))
        if args.dither and visible:
            error = [values[y][x][i]-rgb[i] for i in range(3)]
            for dx,dy,weight in [(1,0,7),(-1,1,3),(0,1,5),(1,1,1)]:
                nx,ny=x+dx,y+dy
                if 0<=nx<16 and ny<16 and icon.getpixel((nx,ny))[3]>=128:
                    for i in range(3):values[ny][nx][i]+=error[i]*weight/16
    mask.append(row)
metadata = {'name': args.name, 'icon': {'size':16, 'rows':mask, 'rgb565':base64.b64encode(packed).decode()}}
digest = hashlib.sha256(args.source.read_bytes()).hexdigest()
credit = args.credit.replace('\n',' ').replace('*/','')
content = f'/** Original: {credit}. Source SHA-256: {digest}.\n * 16x16 Lanczos / {args.palette.upper()} palette, packed RGB565' + (' / Floyd-Steinberg' if args.dither else '') + '; generated by scripts/build-harness-icon.py. */\n'
content += 'export const harnessPresentation = ' + json.dumps(metadata,separators=(',',':'),ensure_ascii=False).replace('"size":16','"size":16 as const') + ';\n'
args.output.write_text(content,encoding='utf-8')
if args.preview:
    args.preview.parent.mkdir(parents=True,exist_ok=True)
    preview.save(args.preview)
print(json.dumps({'name':args.name,'size':16,'palette':args.palette,'packedBytes':len(packed),'sourceSha256':digest,'dither':args.dither}))
