'use strict';
const ui={
  ko:{heading:'기기 설정',subtitle:'USB 연결부터 업데이트와 Wi-Fi 설정까지, 이 창에서 진행합니다.',journey:['01 · 기기 확인','02 · 백업 + 업데이트','03 · 자동 재기동','04 · Wi-Fi + LAN 검색'],usb:'USB 기기',refresh:'다시 확인',empty:'',release:'제공 펌웨어',scope:'미들웨어에 포함된 펌웨어 기준입니다. 업데이트 버튼을 누르기 전에는 플래시를 쓰지 않습니다. 빌드 도구가 없으면 다운로드에 시간이 걸릴 수 있습니다.',wifi:'PC의 Wi-Fi 가져오기',readWifi:'연결된 Wi-Fi 확인',noWifi:'가져올 Wi-Fi를 확인하지 못했습니다. 유선 연결, OS 접근 권한 또는 지원되지 않는 보안 방식일 수 있습니다. 아래 기기 안내를 따라 설정할 수 있습니다.',wifiBoundary:'기존에 저장된 Wi-Fi는 덮어쓰지 않습니다. 가져오기를 선택한 경우에만 OS에서 비밀번호를 읽어 USB로 전달하며 화면·로그에 표시하지 않습니다. ',guide:'기기에서 직접 설정하기',caption:'설정 위치를 설명하는 안내 그림입니다. 실시간 기기 화면이 아닙니다.',steps:[],faces:'',current:'현재 버전',unknown:'미확인',available:'제공 버전',unrecognized:'Snowball 펌웨어 응답이 없습니다. 공기계 또는 다른 펌웨어일 수 있습니다.',confirm:'',install:'백업 후 설치',update:'백업 후 업데이트',latest:'최신 제공 버전입니다.',newer:'기기의 버전이 더 높습니다. 자동 다운그레이드하지 않습니다.',saved:'기존 Wi-Fi 보존',connected:'연결됨',notConnected:'저장됨 · 현재 연결 안 됨',needsWifi:'기기에 저장된 Wi-Fi가 없습니다.',unknownWifi:'Wi-Fi 저장 여부는 새 펌웨어 적용 후 확인합니다.',migrate:'이 Wi-Fi 가져오기',unplugged:'USB 연결 끊김',backup:'전체 플래시 백업',complete:'기기 응답 확인 완료',failed:'작업이 완료되지 않았습니다. 백업이 생성되었다면 아래 위치에 보존됩니다. 연결과 드라이버를 확인한 뒤 다시 확인하세요.',phase:{checking:'기기 버전 확인 중…',identify:'ESP32와 플래시 용량 확인 중…',backup:'전체 플래시 백업 중…', 'backup-verified':'백업 크기·해시 확인 완료',build:'펌웨어 준비 중… (누락된 빌드 도구 다운로드 포함)',flash:'펌웨어 업데이트 중… USB 연결을 유지하세요.', 'verify-settings':'기존 설정 저장 영역 검증 중…','verify-nvs':'기존 설정 저장 영역 검증 중…',reboot:'자동 재기동 및 새 펌웨어 응답 확인 중…',wifi:'OS 권한 확인 및 실제 Wi-Fi 연결 확인 중…',complete:'완료',failed:'확인 필요',ready:'준비됨'},busy:'다른 USB 확인/작업이 진행 중입니다. 잠시 후 다시 시도하세요.'},
  en:{heading:'Device setup',subtitle:'USB detection, firmware and Wi-Fi in one window.',journey:['01 · Identify','02 · Back up + update','03 · Reboot','04 · Wi-Fi + LAN discovery'],usb:'USB devices',refresh:'Check again',empty:'',release:'Included firmware',scope:'Uses firmware included with this middleware. Flash is written only after you choose Install / Update. Missing build tools may take time to download.',wifi:'Import this PC’s Wi-Fi',readWifi:'Read connected Wi-Fi',noWifi:'Connected Wi-Fi is unavailable. This PC may use Ethernet, require OS permission or use unsupported security. You can configure the device using the guide below.',wifiBoundary:'Saved device Wi-Fi is never replaced. The OS password is read only when you choose Import and sent over USB; it never appears in the window or logs.',guide:'Set up on the device',caption:'Illustration of the controls, not a live device screen.',steps:[],faces:'',current:'Installed',unknown:'Unknown',available:'Included',unrecognized:'No Snowball firmware response. This may be a blank device or other firmware.',confirm:'',install:'Back up and install',update:'Back up and update',latest:'Matches the included firmware.',newer:'The device has a newer version. No automatic downgrade.',saved:'Saved Wi-Fi retained',connected:'Connected',notConnected:'Saved · currently disconnected',needsWifi:'No network is saved on the device.',unknownWifi:'Saved Wi-Fi status will be checked after the firmware update.',migrate:'Import this Wi-Fi',unplugged:'USB disconnected',backup:'Full flash backup',complete:'Device response verified',failed:'The operation did not complete. Any backup created remains at the location below. Check USB and drivers, then check again.',phase:{checking:'Checking device firmware…',identify:'Checking ESP32 and flash capacity…',backup:'Backing up the entire flash…','backup-verified':'Backup size and hash verified',build:'Preparing firmware… (including missing build tools)',flash:'Updating firmware… Keep USB connected.','verify-settings':'Verifying retained settings…','verify-nvs':'Verifying retained settings…',reboot:'Rebooting and checking new firmware…',wifi:'Waiting for OS permission and real Wi-Fi association…',complete:'Complete',failed:'Needs attention',ready:'Ready'},busy:'A USB check or operation is in progress. Try again shortly.'}
};
const failureText={ko:{backup_incomplete:'전체 백업이 완료되지 않아 펌웨어 쓰기를 시작하지 않았습니다.',nvs_layout_incompatible:'기존 저장 영역 배치가 호환되지 않아 펌웨어를 쓰지 않았습니다. 전체 백업은 보존됩니다.',nvs_preservation_failed_restore_backup:'저장 영역 보존 검증에 실패했습니다. 보존된 전체 백업으로 복원이 필요합니다.',original_core_required:'선택한 기종과 실제 기기를 확인하세요.',wifi_changed_review_again:'PC의 연결된 Wi-Fi가 바뀌었습니다. 연결 정보를 다시 확인하세요.',wifi_connection_unconfirmed:'Wi-Fi 연결을 확인하지 못했습니다. 아래 기기 안내로 설정을 확인하세요.',wifi_key_permission_required:'OS가 비밀번호 읽기를 허용하지 않았습니다. 기기에서 직접 설정할 수 있습니다.',usb_device_changed:'USB 기기가 바뀌었습니다. 다시 확인한 뒤 진행하세요.'},en:{backup_incomplete:'Full backup did not complete; firmware was not written.',nvs_layout_incompatible:'Existing storage layout is incompatible. Firmware was not written; the full backup remains.',nvs_preservation_failed_restore_backup:'Storage preservation failed. Restore the retained full flash backup.',original_core_required:'Confirm the selected model matches the physical device.',wifi_changed_review_again:'The PC changed Wi-Fi networks. Review the connected network again.',wifi_connection_unconfirmed:'Wi-Fi association is unconfirmed. Follow the device guide below.',wifi_key_permission_required:'OS password access was denied. Configure Wi-Fi on the device instead.',usb_device_changed:'The USB device changed. Check it again before continuing.'}};
const $=id=>document.getElementById(id);let language='ko',snapshot={devices:[],release:{version:'…',changes:{}}},hubState={profiles:[]},selectedProfile,lastRequestedProfile,error='';const approved=new Set(),declinedWifi=new Set();
function element(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function relation(a,b){const x=String(a??'').split('.').map(Number),y=String(b??'').split('.').map(Number);if(x.length!==3||x.some(Number.isNaN))return 'unknown';for(let i=0;i<3;i++)if(x[i]!==y[i])return x[i]<y[i]?'older':'newer';return 'current';}
async function action(request){error='';try{accept(await window.snowballSetup.action({...request,profile:selectedProfile}));}catch{error=ui[language].busy;}render();}
function render(){
  const base=ui[language],p=snapshot.presentation?.[language],t={...base,empty:p?.connection??'',confirm:p?.confirmation??'',steps:p?.steps??[],faces:p?.note??''};
  $('profile-label').textContent=language==='ko'?'기기 종류':'Device type';
  $('profile').replaceChildren(...hubState.profiles.map(profile=>{const option=element('option',profile.name);option.value=profile.profile;return option;}));$('profile').value=selectedProfile??'';
  $('wifi-section').hidden=!snapshot.capabilities?.wifiImport;renderDiagram(p?.diagram);document.documentElement.lang=language;$('heading').textContent=t.heading;$('subtitle').textContent=t.subtitle;
  for(const [id,value]of Object.entries({'usb-title':t.usb,refresh:t.refresh,'release-title':`${t.release} · ${snapshot.release.version}`,'scope':t.scope,'wifi-title':t.wifi,'read-wifi':t.readWifi,'wifi-boundary':t.wifiBoundary,'guide-title':t.guide,'guide-caption':t.caption,'faces-note':t.faces}))$(id).textContent=value;
  $('journey').replaceChildren(...t.journey.map(s=>element('span',s)));$('changes').replaceChildren(...(snapshot.release.changes[language]??[]).map(s=>element('li',s)));
  $('guide-steps').replaceChildren(...t.steps.map(s=>element('li',s)));$('notice').textContent=error||(snapshot.code?t.noWifi:'');
  $('network').textContent=snapshot.network?`Wi-Fi · ${snapshot.network.ssid}${snapshot.network.enterprise?' · Enterprise (manual setup)':''}`:t.noWifi;
  $('refresh').disabled=$('read-wifi').disabled=!!snapshot.busy;
  const cards=snapshot.devices.map(device=>{
    const card=element('article',undefined,'device');card.append(element('strong',`${device.port} · ${device.hello?.deviceId??device.label}`));
    if(!device.online)card.append(element('p',t.unplugged,'error'));
    const versions=element('div',undefined,'versions');
    for(const [label,version]of [[t.current,device.hello?.firmware??t.unknown],[t.available,snapshot.release.version]]){if(versions.childElementCount)versions.append(element('span','→','arrow'));const box=element('div',undefined,'version');box.append(element('small',label),element('strong',version));versions.append(box);}card.append(versions);
    const status=relation(device.hello?.firmware,snapshot.release.version);
    if(!device.hello)card.append(element('p',t.unrecognized));
    if(status==='current'||status==='newer')card.append(element('p',status==='current'?t.latest:t.newer,'muted'));
    if(device.hello?.wifiConfigured===true)card.append(element('p',`${t.saved} · ${device.hello.wifiSsid??''} · ${device.hello.wifiConnected?t.connected:t.notConnected}`));
    else card.append(element('p',device.hello?.wifiConfigured===false?t.needsWifi:t.unknownWifi));
    const actions=element('div',undefined,'actions');
    if(['older','unknown'].includes(status)){
      const check=element('label',undefined,'check'),input=element('input');input.type='checkbox';input.checked=approved.has(selectedProfile+device.port);input.disabled=!!snapshot.busy;check.append(input,element('span',t.confirm));card.append(check);
      let importWifi=null;if(snapshot.capabilities?.wifiImport&&snapshot.network&&!snapshot.network.enterprise&&device.hello?.wifiConfigured!==true){const label=element('label',undefined,'check');importWifi=element('input');importWifi.type='checkbox';importWifi.checked=!declinedWifi.has(selectedProfile+device.port);importWifi.disabled=!!snapshot.busy;importWifi.addEventListener('change',()=>{importWifi.checked?declinedWifi.delete(selectedProfile+device.port):declinedWifi.add(selectedProfile+device.port);});label.append(importWifi,element('span',language==='ko'?"저장된 Wi-Fi가 없으면 업데이트 후 PC Wi-Fi("+snapshot.network.ssid+" )를 가져옵니다.":"If no Wi-Fi is saved, import this PC’s network ("+snapshot.network.ssid+" ) after the update."));card.append(label);}const install=element('button',device.hello?t.update:t.install);const updateEnabled=()=>{install.disabled=!input.checked||snapshot.busy||snapshot.checking||!device.online||device.phase==='checking';};input.addEventListener('change',()=>{input.checked?approved.add(selectedProfile+device.port):approved.delete(selectedProfile+device.port);updateEnabled();});updateEnabled();install.addEventListener('click',()=>action({action:'install',port:device.port,version:snapshot.release.version,confirmBoard:true,migrateWifi:importWifi?.checked===true,...(importWifi?.checked?{ssid:snapshot.network.ssid}:{})}));actions.append(install);
    }
    if(snapshot.capabilities?.wifiImport&&device.hello?.usbSetup===true&&device.hello.wifiConfigured===false){const migrate=element('button',t.migrate);migrate.disabled=!snapshot.network||snapshot.network.enterprise||snapshot.busy||!device.online;migrate.addEventListener('click',()=>action({action:'migrate',port:device.port,ssid:snapshot.network.ssid}));actions.append(migrate);}
    card.append(actions);
    if(!['ready',undefined].includes(device.phase)){const progress=element('div',undefined,'progress');progress.setAttribute('role','status');progress.append(element('p',t.phase[device.phase]??device.phase));if(device.phase==='failed')progress.append(element('p',`${failureText[language][device.code]??t.failed} (${device.code??'usb_operation_failed'})`,'error'));if(device.backup)progress.append(element('p',`${t.backup}: ${device.backup}`,'muted'));card.append(progress);}
    return card;
  });$('devices').replaceChildren(...(cards.length?cards:[element('p',t.empty,'muted')]));
}
function accept(state){hubState=state;if(state.selectedProfile&&state.selectedProfile!==lastRequestedProfile){selectedProfile=state.selectedProfile;lastRequestedProfile=state.selectedProfile;}if(!state.profiles.some(p=>p.profile===selectedProfile))selectedProfile=state.profiles[0]?.profile;const active=state.profiles.find(p=>p.profile===selectedProfile);snapshot=active?{...active,busy:state.busy,checking:state.checking}:{devices:[],release:{version:'…',changes:{}}};}
function renderDiagram(diagram){
  const svg=$('device-diagram');svg.replaceChildren();if(!diagram)return;
  const add=(tag,attributes,text)=>{const node=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [key,value]of Object.entries(attributes))node.setAttribute(key,value);if(text!==undefined)node.textContent=text;svg.append(node);};
  add('rect',{x:25,y:8,width:260,height:210,rx:22,fill:'#252b33',stroke:'#636d7b','stroke-width':3});add('rect',{x:43,y:26,width:224,height:139,rx:6,fill:'#10151c'});
  add('text',{x:59,y:55,fill:'#a3e17d','font-size':17},diagram.title);add('rect',{x:54,y:67,width:202,height:31,rx:4,fill:'#a3e17d'});add('text',{x:62,y:88,fill:'#10151c','font-size':15},diagram.selection);add('text',{x:61,y:124,fill:'#a0aab8','font-size':13},diagram.hint);
  const width=210/Math.max(1,diagram.buttons.length);diagram.buttons.forEach((label,i)=>{add('rect',{x:50+i*width,y:181,width:width-8,height:23,rx:6,fill:'#434e5c'});add('text',{x:50+i*width+(width-8)/2,y:198,fill:'#eef1f4','font-size':14,'text-anchor':'middle'},label);});
}
$('profile').addEventListener('change',event=>{selectedProfile=event.target.value;accept(hubState);render();if(snapshot.capabilities?.wifiImport)void action({action:'wifi'});});
$('language').addEventListener('change',event=>{language=event.target.value;render();});$('refresh').addEventListener('click',()=>action({action:'refresh'}));$('read-wifi').addEventListener('click',()=>action({action:'wifi'}));
window.snowballSetup.subscribe(state=>{accept(state);render();});
window.snowballSetup.snapshot().then(state=>{accept(state);language=state.language==='en'?'en':'ko';$('language').value=language;render();if(snapshot.capabilities?.wifiImport)void action({action:'wifi'});});
